version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=dinedesk_user
      - DB_PASSWORD=secure_password
      - DB_NAME=dinedesk_db
      - DB_PORT=3306
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=dinedesk_db
      - MYSQL_USER=dinedesk_user
      - MYSQL_PASSWORD=secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup-database.js:/docker-entrypoint-initdb.d/setup-database.js
    restart: unless-stopped

volumes:
  mysql_data:
